Omit row action menu for deleted rows
unfoldingWord/datatable-translatable pull request #66
Opened 2021-07-06 16:16 UTC by mandolyte

2021-07-06 16:20 UTC, mandolyte commented
Testing Notes:
- login
- org unfoldingWord
- resource tN
- language English
- book Jude (as of this writing Jude has deleted rows)
- set rows per page to 100
- scroll down to end of file
- Notice that for deleted rows (no values on target side), the row action menu is absent.

Test row recovery:
- for a deleted row, enter a value for support reference
- click out
- at this point, the row will be recovered and moved to the end of the target file data, above its deleted rows. The action menu will be restored for the row.

2021-07-07 11:29 UTC, mandolyte commented
@ancientTexts-net NOTE! this issue did not require any changes to tc-create itself. Only datatable-translatable. Thus yalc should work easily for testing.

2021-07-13 04:34 UTC, ancientTexts-net requested changes

2021-07-13 04:34 UTC, ancientTexts-net commented on src/components/actions-menu/ActionsMenu.js
> +  if ( cellvals[0] !== cellvals[1] ) {
Putting comment in ISSUE with screenshot:

Seems the Actions Menu is also removed from rows that are INSERTED in target, 
but don't exist in the SOURCE.

Is this desired behavior please?

Thanks

2021-07-13 04:34 UTC, ancientTexts-net commented
@mandolyte 

Seems the Actions Menu is also removed from rows that are INSERTED in target,
but don't exist in the SOURCE.

Is this desired behavior please?

Thanks



![image.png](https://images.zenhubusercontent.com/5ec297799c61301f66b0725c/e9a7b304-d815-45e7-a419-dcdf7cdf9882)

2021-07-13 13:25 UTC, mandolyte commented
No! not the desired behavior. Glad you caught that. I had to refine my test to determine if a row is deleted or not. The new test (also in code comments) is this:
```js
  // If a row is deleted (as opposed to being a new add/insert), then
  // source side will *not* be empty, but the target side will be empty.
  let cellvals = []
  cellvals = rowData[1].split('\t')
  // is this a deleted row?
  if ( cellvals[0] !== "" && cellvals[1] === "" ) {
    return (
      <>
      </>
    )
  }
```

2021-07-20 05:07 UTC, ancientTexts-net commented
___
*[src/components/actions-menu/ActionsMenu.js, line 65 at r1](https://reviewable.io/reviews/unfoldingword/datatable-translatable/66#-MdwargID5wHs4MAkq63-r1-65:-Mf1IrYU9-PLzL0Lqk5K:bb6ywmx) ([raw file](https://github.com/unfoldingword/datatable-translatable/blob/39e3d5c4281d81977dbfaada60d6b8d437ce96d9/src/components/actions-menu/ActionsMenu.js#L65)):*
<details><summary><i>Previously, ancientTexts-net (Zach P) wrote…</i></summary><blockquote>

Putting comment in ISSUE with screenshot:

Seems the Actions Menu is also removed from rows that are INSERTED in target, 
but don't exist in the SOURCE.

Is this desired behavior please?

Thanks
</blockquote></details>

LGTM


<!-- Sent from Reviewable.io -->

2021-07-20 05:07 UTC, ancientTexts-net approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/datatable-translatable/66)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mandolyte)



<!-- Sent from Reviewable.io -->

2021-07-20 05:07 UTC, merged

2021-07-20 05:20 UTC, ancientTexts-net reviewed
LGTM