Removed text from dialog
unfoldingWord/datatable-translatable pull request #67
Opened 2021-07-08 15:53 UTC by mandolyte

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/datatable-translatable/67)

2021-07-13 03:50 UTC, ancientTexts-net requested changes

2021-07-13 03:50 UTC, ancientTexts-net commented on src/components/actions-menu/AddRow.js
>            <DialogContentText id="dialog-description">
Should we remove the DialogContentText tag too?  Or is that required?
Thanks

2021-07-13 13:42 UTC, mandolyte reviewed
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/datatable-translatable/67)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ancientTexts-net)

___
*[src/components/actions-menu/AddRow.js, line 81 at r1](https://reviewable.io/reviews/unfoldingword/datatable-translatable/67#-Me5ooFJDcev6C7Lj6Kp-r1-81:-MeV5bZ29vg27dArbsGg:b-896fix) ([raw file](https://github.com/unfoldingword/datatable-translatable/blob/2cf0235372194856953d61a6e4ff71ee91740f19/src/components/actions-menu/AddRow.js#L81)):*
<details><summary><i>Previously, ancientTexts-net (Zach P) wrote…</i></summary><blockquote>

Should we remove the DialogContentText tag too?  Or is that required?
Thanks
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-20 05:17 UTC, ancientTexts-net reviewed
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/unfoldingword/datatable-translatable/67)* status: all files reviewed, 1 unresolved discussion (waiting on @ancientTexts-net)



<!-- Sent from Reviewable.io -->

2021-07-20 05:18 UTC, ancientTexts-net approved these changes

2021-07-20 05:18 UTC, merged